pruebas_index:
    path: /pruebas/{lang}/{name}/{page}
    defaults: { _controller: AppBundle:pruebas:index, lang:es, name:Alexander, page:1 }
    methods: [GET]
    requirements: 
        name: "[a-zA-Z]*"
        page: \d+
        lang: es|en
        
    